on:
  push:
    branches:
     - main

jobs:
  jagexappletviewer:
    name: Build Jagex Applet Viewer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: gradle build

    - run: sha256sum jagexappletviewer/build/libs/jagexappletviewer.jar | cut -d ' ' -f 1 | tr -d '\n' > jagexappletviewer/build/libs/jagexappletviewer.jar.sha256

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: jagexappletviewer
        path: |
          jagexappletviewer/build/libs/*
